name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: 'antonarbus'
  REGION: 'us-central1'
  ARTIFACTS_REGISTRY_FOLDER: 'artifact-registry'
  DOCKER_IMAGE_NAME: 'docker-image'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker '${{ env.REGION }}-docker.pkg.dev'

      - name: Set environment variables
        run: |
          echo "IMAGE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfile.prod
          push: true
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACTS_REGISTRY_FOLDER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: cloud-run-${{ env.IMAGE_VERSION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACTS_REGISTRY_FOLDER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          region: ${{ env.REGION }}
          project_id: ${{ env.PROJECT_ID }}

      - name: 'Show output'
        run: |2-
          echo ${{ steps.deploy.outputs.url }}
